name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :app:dexguardApkRelease

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
            artifacts: "app/build/outputs/apk/release/*"
            tag: v1.0.${{ github.run_number }}
            token: ${{ secrets.TOKEN }}

